# workflow.py (temporary shim) - safe dummy that generates a small PDF
import os
from fpdf import FPDF
from datetime import datetime

PDF_DIR = "generated_pdfs"
os.makedirs(PDF_DIR, exist_ok=True)

def process_workflow(url, query):
    # create a tiny PDF to simulate a real run
    fname = f"dummy_{int(datetime.utcnow().timestamp())}.pdf"
    path = os.path.join(PDF_DIR, fname)
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    pdf.cell(0, 10, f"URL: {url}", ln=1)
    pdf.cell(0, 10, f"Query: {query}", ln=1)
    pdf.cell(0, 10, "This is a temporary dummy PDF generated by workflow shim.", ln=1)
    pdf.output(path)
    return path
